[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.devnet]
decentralized_lottery = "9G1iJ7M8fNotapwrW9o9EgB3EeobrzHPyL8kgmQGQGvz"

[programs.localnet]
decentralized_lottery = "BH1qtDhU6PtB1jrUJPf8JoN34ELuTvVTDktDLFyq2JV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
