[package]
name = "decentralized-lottery"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "decentralized_lottery"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-log-ix-name = []
idl-build = []
no-log-data = []
anchor-debug = []
custom-heap = []
custom-panic = []
no-idl = []

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
anchor-derive-space = "0.30.1"
spl-token = { workspace = true }
spl-associated-token-account = { workspace = true }
thiserror = "1.0"
num-derive = "0.4.2"
solana-program = { workspace = true }
# Temporarily comment out switchboard until we resolve import issues
# switchboard-solana = "0.30.4"

[package.metadata.anchor]
program = { name = "decentralized_lottery", id = "7my34Pj4c96UfSieKESvNZ8napKonpZAiBxUum1VbGS3" }